### ISSUE TITLE
Is it possible to make a "prevent this page from creating additional dialogs" mode in Confirm Mode?

### ISSUE THREAD

**Issue by AltAccountReasons** [Baptistou/PopupFilter#3]
Like this https://i.stack.imgur.com/HDhXB.png when a page is spamming redirects and popups.
Hope you don't mind the suggestion.

**Comment by AltAccountReasons** [comment]
Also loving the extension so much!

**Comment by Baptistou** [comment]
Hi ! Thank you for your comment :)

I did some tests and noticed the following main disadvantage: If PopupFilter prevents a page from creating additional tabs in Confirm Mode, this will also prevents the user from opening a legitimate link to a new tab, which is quite annoying.
Moreover, this suggestion looks like what is already done by Blocking Mode. When I am confronted to this kind of situation where a website is spamming popups, I usually switch mode to the latter.

I prefer to keep a very permissive Confirm Mode as opposed to a very restrictive Blocking Mode, that you can easily switch to depending of the situation. Therefore I will close this issue.
